<?php include"includes/header2.php" ?>

<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				  <ul class="nav navbar-nav">
					<li><a href="index.php">Home</a></li>
					<li><a href="about.php">About</a></li>
					<li><a href="services.php">Services</a></li>
					<li><a class="active" href="products.php">Products</a></li>
					<li><a href="career.php">Career</a></li>
					<li><a href="contact.php">Contact</a></li>
				  </ul>
				</div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		<!-- //navigation -->
	</header>
	<!-- //header -->
	<!-- banner -->
	<div class="agile-banner">
		<div class="container">
		  <div class="row">
			<h2 class="w3ls_header"><span>Products</span></h2>
		  </div>
	  	</div>
	</div>
	<!-- //banner -->
	<!-- products -->
	<div class="agile-prod">
	<div class="container">
		
		<div class="agile-prod1">
			<div class="col-md-6 agile-sub">
				<h4>Solar Street Light</h4>
				<p>Our street lighting range is diverse from 7W to 100W and with innovative features such as anti-theft protection, dimming option, different battery options, super bright LEDs and attractive design.</p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Automatic ON/OFF (Dusk to Dawn).</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>CFL and LED based lights</a></li>
				</ul>
			</div>
			<div class="col-md-6 agile-img">
				<img src="images/streetlight.jpg" alt="image">
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
		<div class="agile-prod1">
			<div class="col-md-6 agile-img">
				<img src="images/g6.jpg" alt="image">
			</div>
			<div class="col-md-6 agile-sub">
				<h4>Solar Micro Grid</h4>
				<p>Used for Solarizing unelectrified households & villages,
				Centralised electricity generation & transmission.
				Utility model to supply electricity & collection at monthly or weekly level.
				<!-- <br>Robust system & better economies of scale --></p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Microgrids to power productive loads</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>System size may range from 200W to 20KW</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
		<div class="agile-prod1">
			<div class="col-md-6 agile-sub">
				<h4>SOLAR ROOFTOP SYSTEM</h4>
				<p>A market leader in Solar Rooftop Systems, Solar Tree focuses on significant reducing electricity costs for its customers, attractive payback, hassle free operation & maintenance and affordability through financing.
				</p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Capex (Asset ownership and upfront investment)</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Opex (zero investment and pay per use)</a></li>
				</ul>
			</div>
			<div class="col-md-6 agile-img">
				<img src="images/g8.jpg" alt="image">
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
		<div class="agile-prod1">
			<div class="col-md-6 agile-img">
				<img src="images/wh.jpg" alt="image">
			</div>
			<div class="col-md-6 agile-sub">
				<h4>Solar Water Heater</h4>
				<p>We are suppliers of solar water heating systems with Flat Plate Collectors (FPC), Evacuated tube Collector (ETC) systems. We are involved in alternative energy solution and has developed a wide range of efficient products.</p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Heat water up to 55°C to 70°C</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Low-cost long-term solution</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
		<div class="agile-prod1">
			<div class="col-md-6 agile-sub">
				<h4>SOLAR water pump</h4>
				<p>Solar Water Pumping system is a water lifting system powered by electricity generated by Solar panels. There are two types of Solar Water Pumps, one is Submersible Solar Pump and another is Surface Solar Pump. 
				</p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Available in DC and AC</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>More economical where grid electricity not available</a></li>
				</ul>
			</div>
			<div class="col-md-6 agile-img">
				<img src="images/g1.jpg" alt="image">
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
		<div class="agile-prod1">
			<div class="col-md-6 agile-img">
				<img src="images/g6.jpg" alt="image">
			</div>
			<div class="col-md-6 agile-sub">
				<h4>Solar Air Conditioner</h4>
				<p>Solar AC is very environment-friendly and it reduces grid power consumption to 100%.The only difference is existing AC use only electricity grid, where Hybrid Solar AC uses Solar Power, Battery Bank, Electricity grid.</p>
				<ul>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a> Complete app-based control</a></li>
					<li><i class="fa fa-check-circle" aria-hidden="true"></i> <a>Zero Electricity Bill and low maintenance</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="black-div"></div>
		</div>
	</div>
</div>
<!-- //products -->
<?php include"includes/footer.php" ?>