<?php include"includes/header2.php" ?>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				  <ul class="nav navbar-nav">
					<li><a href="index.php">Home</a></li>
					<li><a href="about.php">About</a></li>
					<li><a class="active" href="services.php">Services</a></li>
					<li><a href="products.php">Products</a></li>
					<li><a href="career.php">Career</a></li>
					<li><a href="contact.php">Contact</a></li>
				  </ul>
				</div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		<!-- //navigation -->
	</header>
	<!-- //header -->
	<!-- banner -->
	<div class="agile-banner">
	  <div class="container">
		<div class="row">
			<h2 class="w3ls_header"><span>Services</span></h2>
		</div>
	  </div>
	</div>
	<!-- //banner -->
	 <!-- agileinfo --> 
	<div class="agileinfo">
				<div class="container">
				
				<div class="services-grids">
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>01</p>
							</div>
							<div class="services-right">
								<h4>On-Grid 1Kw-10Kw</h4>
								<p>Companies dislike the term ‘turnaround consulting’ because it represents failure. The truth is that turnaround consulting represents success. </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>02</p>
							</div>
							<div class="services-right">
								<h4>Off-Grid 1Kw-10Kw</h4>
								<p>Bonds and commodities are much more stable than stocks and trades. We allow our clients to invest in the right bonds & commodities. </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>03</p>
							</div>
							<div class="services-right">
								<h4>Hybrid 1 Kw- 10Kw</h4>
								<p>Audit and assurance is all about meticulous data analysis. Everything needs to be checked, double checked, and triple checked. </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>04</p>
							</div>
							<div class="services-right">
								<h4>On-Grid 20Kw-100Kw</h4>
								<p>This allows us to specialize in all dimensions of trades and stocks, because we have a specialist within the team for every scenario.  </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>05</p>
							</div>
							<div class="services-right">
								<h4>1mW Power Plant</h4>
								<p>We work with our clients and do a deep analysis of their business. We help prepare possible outcomes to different decisions. </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="col-md-4 services-grid">
							<div class="services-left">
								<p>06</p>
							</div>
							<div class="services-right">
								<h4>All Solar Power Plants</h4>
								<p>This stops companies from taking drastic measures like downsizing or closing down sites; those things happen only with no or bad financial projections.  </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="clearfix"></div>
				</div>
				</div>
			</div>
<!-- //agileinfo -->
<!-- overview --> 
	<div class="overview w3-2">
			<div class="container">
			<h3 class="w3ls_head"><span>Services Overview</span></h3>
				<div class="overview-grids">
					<div class="col-md-4 list-grid">
						<div class="list-img">
							<img src="images/streetlight.jpg" class="img-responsive" alt=" ">
							<div class="textbox"></div>
						</div>						
						<h4>Solar Street Light</h4>
						<p>A Battery based Solar Street is a stand alone system, will store electricity from Solar Panels .Solar street lights are  powered by photovoltaic panels generally mounted on the lighting structure or integrated in the pole itself. </p>
					</div>
					<div class="col-md-4 list-grid">
						<div class="list-img">
							<img src="images/wh.jpg" class="img-responsive" alt=" ">
							<div class="textbox"></div>
						</div>	
						<h4>Solar Water Heaters</h4>
						<p>Solar water heaters use the Sun’s energy to heat water during the day. This water is stored inside an insulated tank for use whenever required. The Sunrays have enough energy to heat water up to 55°C to 70°C which is more than sufficient for bathing.</p>
					</div>
					<div class="col-md-4 list-grid">
						<div class="list-img">
							<img src="images/g1.jpg" class="img-responsive" alt=" ">
							<div class="textbox"></div>
						</div>	
						<h4>Solar Water Pumps</h4>
						<p>Solar Water Pumping system is a water lifting system powered by electricity generated by Solar panels. There are two types of Solar Water Pumps, one is Submersible Solar Pump and another is Surface Solar Pump.Both pumps are available in DC and AC. </p>
					</div>
					
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
<!-- //overview --> 
	<!-- main-services--> 
	<div class="main-services agileits-2">
			<div class="container">
			<h3 class="w3ls_head"><span>Main Services</span></h3>
					<div class="services-grids">
						<div class="col-md-3 ser-grid">
							<h4>On- Grid 1Kw-10Kw</h4>
							<ul>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Easy to Install</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>No Maintenance</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Real-time system assessment</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Accelerated depreciation i.e. 80 %</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>One time Investment</li>
							</ul>
						</div>
						<div class="col-md-3 ser-grid">
							<h4>Off- Grid 1Kw-10Kw</h4>
							<ul>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Completely Energy Independent</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>No Power Outage</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Zero Electricity Bills</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Can be Installed Virtually</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Contribute to Environment</li>
							</ul>
						</div>
						<div class="col-md-3 ser-grid">
							<h4>On-Grid 20Kw-100Kw</h4>
							<ul>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i> Govt. Subsidies available-30% to 70%</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Utilise the 100% power</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>reduce power and diesel consumption</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Grid connection with Net metering</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>System for larger power consumers</li>
							</ul>
						</div>
						<div class="col-md-3 ser-grid">
							<h4>1mW Power Plant</h4>
							<ul>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Capacity of power plant - 1 MW</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Easy to install</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Save electricity bill</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>Contribute to Environment</li>
								<li><i class="fa fa-check-circle" aria-hidden="true"></i>One time Investment</li>
							</ul>
						</div>
						<div class="clearfix"></div>
					</div>
				
				
			</div>
		</div>
		
<!-- //main-services --> 
<?php include"includes/footer.php" ?>...